# Generated by Django 3.0.4 on 2020-05-05 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Question'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('session', 'partecipant', 'question')},
        ),
    ]
