# Generated by Django 3.0.4 on 2021-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='text'),
        ),
    ]
