# Generated by Django 3.0.4 on 2020-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20200505_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ui_view',
            field=models.CharField(choices=[('grid', 'grid'), ('list', 'list')], default='grid', max_length=10, verbose_name='ui view'),
            preserve_default=False,
        ),
    ]
