# Generated by Django 3.0.4 on 2020-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
            preserve_default=False,
        ),
    ]
