# Generated by Django 3.0.4 on 2021-06-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20210612_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='note',
            field=models.TextField(blank=True, max_length=2000, verbose_name='text'),
        ),
    ]
