# Generated by Django 3.0.4 on 2020-05-10 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_ui_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partecipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipants', to='quizzes.QuizSession'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='name'),
        ),
    ]
