# Generated by Django 3.0.4 on 2021-06-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='note',
            field=models.TextField(blank=True, max_length=2000, verbose_name='note'),
        ),
    ]
