# Generated by Django 3.0.4 on 2020-04-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20200404_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.Question', verbose_name='current question'),
        ),
    ]
