# Generated by Django 3.0.4 on 2020-05-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20200510_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecipant',
            name='color',
            field=models.CharField(default='#8E76AC', max_length=8, verbose_name='color'),
            preserve_default=False,
        ),
    ]
