# Generated by Django 3.0.4 on 2020-04-18 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0005_quizsession_current_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='position',
            field=models.PositiveIntegerField(blank=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(blank=True, verbose_name='position'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Answer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answers', to='quizzes.QuizSession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user answer',
                'verbose_name_plural': 'user answers',
            },
        ),
    ]
