# Generated by Django 3.0.4 on 2020-05-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_partecipant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='stream_link',
            field=models.URLField(default='https://www.twitch.tv/patrickpy/', help_text='Link used for the bottom bar in the quiz', verbose_name='stream link'),
            preserve_default=False,
        ),
    ]
