# Generated by Django 3.0.4 on 2020-05-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quizsession_stream_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='current_question_changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='current question changed at'),
        ),
    ]
