# Generated by Django 3.0.4 on 2020-05-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quizsession_current_question_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='seconds_to_answer_question',
            field=models.PositiveIntegerField(default=30, verbose_name='seconds to answer question'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='current_question_changed',
            field=models.DateTimeField(blank=True, help_text='Users have', null=True, verbose_name='current question changed at'),
        ),
    ]
