# Generated by Django 3.0.4 on 2020-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20200521_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, help_text='If provided, it will be used instead of the text. Please provide a text description for accessibility reasons', null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='text'),
        ),
    ]
