# Generated by Django 3.0.4 on 2020-05-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20200522_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='image height'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='image width'),
        ),
        migrations.AddField(
            model_name='answer',
            name='small_image',
            field=models.BinaryField(blank=True, null=True, verbose_name='small image'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='current_question_changed',
            field=models.DateTimeField(blank=True, help_text="Users have 'seconds_to_answer_question' seconds from this datetime to answer the question", null=True, verbose_name='current question changed at'),
        ),
    ]
