# Generated by Django 3.0.4 on 2020-05-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_auto_20200523_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_format',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='image format'),
        ),
    ]
