# Generated by Django 3.0.4 on 2020-05-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_answer_image_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='small_image',
            field=models.TextField(blank=True, null=True, verbose_name='small image'),
        ),
    ]
