# Generated by Django 3.0.4 on 2020-05-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_auto_20200524_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ui_view',
            field=models.CharField(choices=[('grid', 'grid'), ('list', 'list')], default='grid', max_length=10, verbose_name='ui view'),
        ),
    ]
