# Generated by Django 3.0.4 on 2020-05-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_auto_20200524_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points_to_give',
            field=models.PositiveIntegerField(default=1, verbose_name='points to give'),
        ),
    ]
