name: Backend Tests
on: [push]

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8.2"
      - run: pip install poetry
      - name: Cache Poetry
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}-v3
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}-v3
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Install python dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Pytest
        run: poetry run pytest
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports['5432'] }}/postgres
